{"status": "FAILURE", "result": {"exc_type": "ValueError", "exc_message": ["TEST ERROR!!!!"], "exc_module": "builtins"}, "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/dist-packages/celery/app/trace.py\", line 385, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/celery/app/trace.py\", line 648, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/home/alex/code/roomster-2-proto/6-rabbitmq/rabbit-test/tasks.py\", line 13, in add\n    raise ValueError('TEST ERROR!!!!')\nValueError: TEST ERROR!!!!\n", "children": [], "task_id": "d5ce61a5-b6a0-42bc-86c8-6a08d8f816b3", "date_done": "2019-08-08T13:40:04.421177"}