{"status": "FAILURE", "result": {"exc_type": "ValueError", "exc_message": ["TEST ERROR!!!!"], "exc_module": "builtins"}, "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/dist-packages/celery/app/trace.py\", line 385, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/celery/app/trace.py\", line 648, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/home/alex/code/roomster-2-proto/6-rabbitmq/rabbit-test/tasks.py\", line 19, in add\n    raise ValueError('TEST ERROR!!!!')\nValueError: TEST ERROR!!!!\n", "children": [], "task_id": "75a421cd-dc1f-4d19-9ecf-e8fd8e8ee182", "date_done": "2019-08-08T13:24:41.724609"}